### ISSUE TITLE
ES 2.2.0 Compatibility

### ISSUE THREAD

**Issue by biyuhao** [codelibs/elasticsearch-repository-ssh#4]
Since elasticsearch 2.x has released for a while. I think we can release a version which is compatible with ES-2.x.
I' done a little migration efforts in my fork on branch 2.2.0.
Maybe I can merge it to this repository.
Here is the address.[elasticsearch-repository-ssh/tree/2.2.0](https://github.com/biyuhao/elasticsearch-repository-ssh/tree/2.2.0)

**Comment by marevol** [comment]
Pull Request is welcome :)
